var AdminApp = new TabTemplate();

AdminApp.TABS = [ { id: 'doClients', caption: 'Clients' },
	{ id: 'doUsers', caption: 'Users' }, { id: 'doApplications', caption: 'Applications' },
	{ id: 'doLanguages', caption: 'Languages' }, { id: 'doMailTemplates', caption: 'Mail Templates' } ];

AdminApp.doClients = function(body) { ClientsHandler.init(body); }
AdminApp.doUsers = function(body) { UsersHandler.init(body); }
AdminApp.doApplications = function(body) { ApplicationsHandler.init(body); }
AdminApp.doLanguages = function(body) { LanguagesHandler.init(body); }
AdminApp.doMailTemplates = function(body) { MailTemplatesHandler.init(body); }

var ClientsHandler = new ListTemplate({
	NAME: 'client',
	SINGULAR: 'Client',
	PLURAL: 'Clients',
	RESOURCE: 'clients',
	IDENTIFIER: 'code',
	CAN_ADD: true,
	CAN_EDIT: true,
	COLUMNS: [ new TextColumn('id', 'ID', undefined, true),
		new EditColumn('code', 'Code'), new EditColumn('name', 'Name'),
		new TextColumn('emailPrefix', 'Email Prefix'), new TextColumn('responseHost', 'Response Host'),
		new TextColumn('active', 'Active'),
		new TextColumn('createdAt', 'Created At', 'toDateTime'),
		new TextColumn('updatedAt', 'Updated At', 'toDateTime') ],
	FIELDS: [ new TextField('id', 'ID'),
	    new EditField('code', 'Code', true, false, 64, 50),
		new EditField('name', 'Name', true, false, 128, 50),
		new EditField('emailPrefix', 'Email Prefix', true, false, 32, 30),
		new EditField('responseHost', 'Response Host', true, false, 128, 50),
		new EditField('resumeMinSize', 'Resume Min Size', true, false, 19, 10),
		new EditField('resumeMaxSize', 'Resume Max Size', true, false, 19, 10),
		new BoolField('resumeRequiresExtension', 'Resume Requires Extension?', true),
		new EditField('resumeLocale', 'Resume Locale', true, false, 5, 5),
		new BoolField('answerPurgerEnabled', 'Answer Purger Enabled?', true),
		new BoolField('knockoutChangeAnswersEnabled', 'Can Change Knocked Out Answers?', true),
		new BoolField('autoSubmitCompletedApps', 'Auto Submit Completed Apps?', true),
		new BoolField('autoSubmitKnockedoutApps', 'Auto Submit Knockedout Apps?', true),
		new EditField('careersEmailAddress', 'Careers Email Address', false, false, 255, 50),
		new DropField('defaultLanguageId', 'Select Default Language', true, 'languages', 'defaultLanguageName'),
		new TextField('defaultLanguageName', 'Selected Default Language', undefined, undefined, true),
		new BoolField('active', 'Is Active?', true),
		new TextField('creator', 'Created At', 'toDateTime'),
		new TextField('updater', 'Updated At', 'toDateTime') ] /*,
	SEARCH: {
		NAME: 'client',
		SINGULAR: 'Client',
		PLURAL: 'Clients',
		RESOURCE: 'clients',
		FIELDS: [ new EditField('id', 'ID', false, false, 20, 10),
	  	    new EditField('code', 'Code', false, false, 64, 50),
			new EditField('name', 'Name', false, false, 128, 50),
			new EditField('emailPrefix', 'Email Prefix', false, false, 32, 30),
			new EditField('responseHost', 'Response Host', false, false, 128, 50),
			new RangeField('resumeMinSize', 'Resume Min Size', false, 19, 10),
			new RangeField('resumeMaxSize', 'Resume Max Size', false, 19, 10),
			new ListField('resumeRequiresExtension', 'Resume Requires Extension?', false, 'yesNoOptions', undefined, 'No Search'),
			new EditField('resumeLocale', 'Resume Locale', false, false, 5, 5),
			new ListField('answerPurgerEnabled', 'Answer Purger Enabled?', false, 'yesNoOptions', undefined, 'No Search'),
			new ListField('knockoutChangeAnswersEnabled', 'Can Change Knocked Out Answers?', false, 'yesNoOptions', undefined, 'No Search'),
			new ListField('autoSubmitCompletedApps', 'Auto Submit Completed Apps?', false, 'yesNoOptions', undefined, 'No Search'),
			new ListField('autoSubmitKnockedoutApps', 'Auto Submit Knockedout Apps?', false, 'yesNoOptions', undefined, 'No Search'),
			new EditField('careersEmailAddress', 'Careers Email Address', false, false, 255, 50),
			new DropField('defaultLanguageId', 'Select Default Language', true, 'languages', 'defaultLanguageName'),
			new TextField('defaultLanguageName', 'Selected Default Language', undefined, undefined, true),
			new ListField('active', 'Is Active?', false, 'yesNoOptions', undefined, 'No Search'),
			new DatesField('creator', 'Created At'),
			new DatesField('updater', 'Updated At'),
			new ListField('pageSize', 'Page Size', false, 'pageSizeOptions', 'Number of records on the page', 'Default') ]
	} */
});

var UsersHandler = new ListTemplate({
	NAME: 'user',
	SINGULAR: 'User',
	PLURAL: 'Users',
	RESOURCE: 'users',
	CAN_ADD: true,
	CAN_EDIT: true,
	COLUMNS: [ new TextColumn('identifier', 'ID', undefined, true),
	    new TextColumn('clientName', 'Client'),
		new EditColumn('id', 'Login ID'), new EditColumn('ats_username', 'ATS User Name'),
		new EditColumn('first_name', 'First Name'), new EditColumn('last_name', 'Last Name'),
		new TextColumn('createdAt', 'Created At', 'toDateTime', true), new TextColumn('updatedAt', 'Updated At', 'toDateTime') ],
	FIELDS: [ new TextField('identifier', 'ID'),
	    new DropField('clientId', 'Select Client', true, 'clients', 'clientName'),
	    new TextField('clientName', 'Selected Client', undefined, undefined, true),
		new EditField('id', 'Login ID', true, false, 128, 50),
		new EditField('ats_username', 'ATS User Name', true, false, 128, 50),
		new PassField('ats_password', 'ATS Password', true, false, 64, 50),
		new EditField('email', 'Email Address', false, false, 128, 50),
		new EditField('first_name', 'First Name', false, false, 100, 20),
		new EditField('last_name', 'Last Name', false, false, 100, 25),
		new EditField('address_1', 'Address 1', false, false, 100, 50),
		new EditField('address_2', 'Address 2', false, false, 100, 50),
		new EditField('city', 'City', false, false, 100, 50),
		new EditField('zip', 'Postal Code', false, false, 10, 10),
		new EditField('cellNumber', 'Cell Number', false, false, 25, 20),
		new EditField('homeNumber', 'Home Number', false, false, 25, 20),
		new EditField('webSite', 'Web Site', false, false, 255, 50),
		new TextField('createdAt', 'Created At', 'toDateTime'),
		new TextField('updatedAt', 'Updated At', 'toDateTime') ],
	SEARCH: {
		NAME: 'user',
		SINGULAR: 'User',
		PLURAL: 'Users',
		RESOURCE: 'users',
		FIELDS: [ new EditField('identifier', 'ID', false, false, 32, 32),
			new DropField('clientId', 'Select Client', true, 'clients', 'clientName'),
			new TextField('clientName', 'Selected Client', undefined, undefined, true),
			new EditField('id', 'Login ID', false, false, 128, 50),
			new EditField('ats_username', 'ATS User Name', false, false, 128, 50),
			new PassField('ats_password', 'ATS Password', false, false, 64, 50),
			new EditField('email', 'Email Address', false, false, 128, 50),
			new EditField('first_name', 'First Name', false, false, 100, 20),
			new EditField('last_name', 'Last Name', false, false, 100, 25),
			new EditField('address_1', 'Address 1', false, false, 100, 50),
			new EditField('address_2', 'Address 2', false, false, 100, 50),
			new EditField('city', 'City', false, false, 100, 50),
			new EditField('zip', 'Postal Code', false, false, 10, 10),
			new EditField('cellNumber', 'Cell Number', false, false, 25, 20),
			new EditField('homeNumber', 'Home Number', false, false, 25, 20),
			new EditField('webSite', 'Web Site', false, false, 255, 50),
			new DatesField('createdAt', 'Created At'),
			new DatesField('updatedAt', 'Updated At'),
			new ListField('pageSize', 'Page Size', false, 'pageSizes', 'Number of records on the page') ]
	}
});

var ApplicationsHandler = new ListTemplate({
	NAME: 'application',
	SINGULAR: 'Application',
	PLURAL: 'Applications',
	RESOURCE: 'applications',
	CAN_EDIT: true,
	COLUMNS: [ new TextColumn('id', 'ID', undefined, true),
	           new TextColumn('clientName', 'Client'),
	           new TextColumn('userName', 'User'),
	           new TextColumn('slug', 'Job'),
	           new TextColumn('completed', 'Completed'),
	           new TextColumn('submitted', 'Submitted'),
	           new TextColumn('knockedout', 'Knockedout'),
	           new TextColumn('startedDate', 'Started At', 'toDateTime'),
	           new TextColumn('completedDate', 'Completed At', 'toDateTime') ],
	FIELDS: [ new TextField('id', 'ID'),
	          new TextField('clientName', 'Client'),
	          new TextField('userName', 'User'),
	          new TextField('slug', 'Job'),
	          new TextField('status', 'Status'),
	          new TextField('responseEmail', 'Response Email'),
	          new TextField('biSessionId', 'BI Session ID'),
	          new TextField('source', 'Source'),
	          new TextField('completed', 'Completed?'),
	          new TextField('submitted', 'Submitted?'),
	          new TextField('knockedout', 'Knockedout?'),
	          new TextField('currentQuestionName', 'Current Question'),
	          new TextField('currentQuestionStateName', 'Current Question State'),
	          new TextField('stageName', 'Stage'),
	          new TextField('metadata_source', 'Metadata Source'),
	          new TextField('completedAt', 'Completed At', 'toDateTime'),
	          new TextField('lastAnswerAt', 'Last Answer At', 'toDateTime'),
	          new TextField('createdAt', 'Created At', 'toDateTime'),
	          new TextField('updatedAt', 'Updated At', 'toDateTime') ],
	SEARCH: {
		NAME: 'application',
		SINGULAR: 'Application',
		PLURAL: 'Applications',
		RESOURCE: 'applications',
		FIELDS: [ new EditField('id', 'ID', false, false, 20, 10),
		          new DropField('clientId', 'Select Client', false, 'clients', 'clientName'),
		          new TextField('clientName', 'Selected Client', undefined, undefined, true),
		          new EditField('loginId', 'User', false, false, 128, 50),
		          new EditField('slug', 'Job', false, false, 128, 50),
		          new EditField('status', 'Status', false, false, 255, 50),
		          new EditField('responseEmail', 'Response Email', false, false, 255, 50),
		          new EditField('biSessionId', 'BI Session ID', false, false, 255, 50),
		          new EditField('source', 'Source', false, false, 255, 50),
		          new ListField('completed', 'Completed?', false, 'yesNoOptions', undefined, 'No Search'),
		          new ListField('submitted', 'Submitted?', false, 'yesNoOptions', undefined, 'No Search'),
		          new ListField('knockedout', 'Knockedout?', false, 'yesNoOptions', undefined, 'No Search'),
		          new EditField('currentQuestionAtsId', 'Current Question', false, false, 255, 50),
		          new ListField('currentQuestionStateId', 'Current Question State', false, 'questionStates', undefined, 'No Search'),
		          new ListField('stageId', 'Stage', false, 'stages', undefined, 'No Search'),
		          new EditField('metadata_source', 'Metadata Source', false, false, 255, 50),
		          new DatesField('completedAt', 'Completed At'),
		          new DatesField('lastAnswerAt', 'Last Answer At'),
		          new DatesField('createdAt', 'Created At'),
		          new DatesField('updatedAt', 'Updated At'),
		          new ListField('pageSize', 'Page Size', false, 'pageSizes', 'Number of records on the page') ]
	}
});

var LanguagesHandler = new ListTemplate({
	NAME: 'language',
	SINGULAR: 'Language',
	PLURAL: 'Languages',
	RESOURCE: 'languages',
	CAN_ADD: true,
	CAN_EDIT: true,
	COLUMNS: [ new TextColumn('id', 'ID', undefined, true),
	           new EditColumn('name', 'Name'),
	           new TextColumn('active', 'Active?') ],
	FIELDS: [ new EditField('id', 'ID', true, false, 5, 5),
	          new EditField('name', 'Name', true, false, 64, 50),
	          new BoolField('active', 'Is Active?', true) ] /*,
	SEARCH: {
		NAME: 'language',
		SINGULAR: 'Language',
		PLURAL: 'Languages',
		RESOURCE: 'languages',
		FIELDS: []
	} */
});

var MailTemplatesHandler = new ListTemplate({
	NAME: 'mailTemplate',
	SINGULAR: 'Mail Template',
	PLURAL: 'Mail Templates',
	RESOURCE: 'mailTemplates',
	CAN_ADD: true,
	CAN_EDIT: true,
	COLUMNS: [ new TextColumn('id', 'ID', undefined, true),
	           new TextColumn('clientName', 'Client'),
	           new EditColumn('name', 'Name'),
	           new TextColumn('languageName', 'Language'),
	           new TextColumn('active', 'Active?'),
	           new TextColumn('createdAt', 'Created At', 'toDateTime'),
	           new TextColumn('updatedAt', 'Updated At', 'toDateTime') ],
	FIELDS: [ new TextField('id', 'ID'),
	          new DropField('clientId', 'Select Client', true, 'clients', 'clientName'),
	          new TextField('clientName', 'Selected Client', undefined, undefined, true),
	          new EditField('name', 'Name', true, false, 64, 50),
	          new DropField('languageId', 'Select Language', true, 'languages', 'languageName'),
	          new TextField('languageName', 'Selected Language', undefined, undefined, true),
	          new EditField('subject', 'Subject', false, false, 255, 50),
	          new EditField('body', 'Body', false, true, 60, 10),
	          new BoolField('active', 'Is Active?', true),
	          new TextField('createdAt', 'Created At', 'toDateTime'),
	          new TextField('updatedAt', 'Updated At', 'toDateTime') ],
	SEARCH: {
		NAME: 'mailTemplate',
		SINGULAR: 'Mail Template',
		PLURAL: 'Mail Templates',
		RESOURCE: 'mailTemplates',
		FIELDS: [ new EditField('id', 'ID', false, false, 20, 10),
		          new DropField('clientId', 'Select Client', false, 'clients', 'clientName'),
		          new TextField('clientName', 'Selected Client', undefined, undefined, true),
		          new EditField('name', 'Name', false, false, 64, 50),
		          new DropField('languageId', 'Select Language', false, 'languages', 'languageName'),
		          new TextField('languageName', 'Selected Language', undefined, undefined, true),
		          new EditField('subject', 'Subject', false, false, 255, 50),
		          new EditField('body', 'Body', false, false, 255, 50),
		          new ListField('active', 'Is Active?', false, 'yesNoOptions', undefined, 'No Search'),
		          new DatesField('createdAt', 'Created At'),
		          new DatesField('updatedAt', 'Updated At'),
		          new ListField('pageSize', 'Page Size', false, 'pageSizes', 'Number of records on the page') ]
	}
});
