function Template(){}Template.MODAL_ZINDEX=100;Template.prototype.KILO=1024;Template.prototype.MEGA=1048576;Template.prototype.GIGA=1073741824;
Template.prototype.LISTS={documentSources:[{id:"dropbox",name:"DropBox"},{id:"email",name:"Email"},{id:"googledocs",name:"Google Drive"},{id:"linkedin",name:"LinkedIn"},{id:"user",name:"Text Submission"},{id:"user_file",name:"File Upload"}],documentTypes:[{id:"A",name:"All"},{id:"C",name:"Cover Letter"},{id:"O",name:"Other"},{id:"R",name:"Resume"}],documentTypesX:[{id:"all",name:"All"},{id:"cover_letter",name:"Cover Letter"},{id:"other",name:"Other"},{id:"resume",name:"Resume"}],locationTypes:[{id:"A",
name:"Any"},{id:"L",name:"Latitude/Longitude"},{id:"N",name:"None"},{id:"S",name:"Shape"}],logLevels:[{id:"ALL",name:"All"},{id:"DEBUG",name:"Debug"},{id:"ERROR",name:"Error"},{id:"INFO",name:"Info"},{id:"OFF",name:"Off"},{id:"TRACE",name:"Trace"},{id:"WARN",name:"Warn"}],yesNoOptions:[{id:"true",name:"Yes"},{id:"false",name:"No"}],pageSizes:[{id:10,name:"10"},{id:20,name:"20"},{id:50,name:"50"},{id:100,name:"100"}]};Template.prototype.REGEX_NEW_LINE=/[\n]+/;Template.prototype.REGEX_PATH_PREFIX=/\/$/;
Template.prototype.REGEX_WHITESPACE=/[\s]+/g;Template.prototype.CSS_ACTIONS="actions";Template.prototype.CSS_FIELDS="fields";Template.prototype.CSS_MODAL="modal";Template.prototype.CAPTION_ADD="Add";Template.prototype.CAPTION_BACK="Back";Template.prototype.CAPTION_CANCEL="Cancel";Template.prototype.CAPTION_CLOSE="Close";Template.prototype.CAPTION_IMPORT="Import";Template.prototype.CAPTION_PREVIEW="Preview";Template.prototype.CAPTION_REMOVE="Remove";Template.prototype.CAPTION_SUBMIT="Submit";
Template.prototype.load=function(a){if(void 0!=a)for(id in a)this[id]=a[id]};
Template.prototype.run=function(a,b,c){var d=this;b&&(a.body=b);void 0==c&&(c="post");void 0==a.isModal&&(a.isModal=void 0==a.body);if(a.isModal&&void 0==a.body){var e=document.body;e.insertBefore(b=this.createDiv("Loading ...","modalDialog"),e.firstChild);b=a.body=$(b);b.CENTERED=0;b.center=function(){var a=$(window);this.css("top",(this.top=(a.height()-this.height())/2+a.scrollTop())+"px");this.css("left",(this.left=(a.width()-this.width())/2+a.scrollLeft())+"px");b.css("zIndex",Template.MODAL_ZINDEX++);
this.CENTERED++};b.closeMe=function(){Template.MODAL_ZINDEX-=this.CENTERED;this.remove()}}ProgressBar.start(a);if(void 0!=a.url)this[c](a.url,a.filter,function(b){ProgressBar.stop(a);d.display(a,b)});else ProgressBar.stop(a),d.display(a,a.value);return a};
Template.prototype.display=function(a,b){a.body.empty();var c=this,d=a.isModal;if(d){var e=a.header=this.createHeader();this.addSpan(e,this.getTitle(a));a.body.append($(e));e.appendChild(this.createAnchor("X",function(b){c.handleCancel(a)}));this.makeElementDraggable(a,e)}a.value=b;a.body.append($(this.generate(a)));if(this.onPostLoad)this.onPostLoad(a);d&&a.body.center()};
Template.prototype.get=Template.get=function(a,b,c,d){var e=this;$.ajax(REST_PATH+a,{type:"GET",data:b,cache:!1,dataType:"json",headers:d,success:function(a){c(a)},error:function(a){e.handleError(a,c)}})};Template.prototype.post=Template.post=function(a,b,c){b||(b={});var d=this;$.ajax(REST_PATH+a,{type:"POST",data:JSON.stringify(b),dataType:"json",success:function(a){c(a)},error:function(a){d.handleError(a,c)},contentType:"application/json; charset=UTF-8"})};
Template.prototype.put=Template.put=function(a,b,c,d){b||(b={});var e=this;$.ajax(REST_PATH+a,{type:"PUT",data:JSON.stringify(b),dataType:"json",headers:d,success:function(a){c(a)},error:function(a){e.handleError(a,c)},contentType:"application/json; charset=UTF-8"})};Template.prototype.remove=Template.remove=function(a,b,c,d){var e=this;$.ajax(REST_PATH+a+"/"+b,{type:"DELETE",headers:d,success:function(a){c(a)},error:function(a){e.handleError(a,c)}})};
Template.prototype.handleError=function(a,b){if(403==a.status)LoginHandler.doLogin(function(){me.put(url,filter,b)});else{var c=a.responseText,c=c?JSON.parse(c):{message:a.statusText};c.isError=!0;delete c.stackTrace;b(c)}};Template.prototype.getList=function(a){return this.LISTS[a]};Template.prototype.clean=function(a){var b;for(id in a)"string"==typeof(b=a[id])&&""==b&&delete a[id]};Template.prototype.createImg=function(a,b){var c=document.createElement("img");c.src=a;b&&(c.title=b);return c};
Template.prototype.createImage=function(a,b){var c=document.createElement("img");c.src=IMAGE_PATH+a;b&&(c.title=b);return c};Template.prototype.createAnchor=Template.createAnchor=function(a,b,c){var d=document.createElement("a");d.href="javascript:void(null)";d.onclick=b;b=typeof a;"string"==b||"number"==b?d.innerHTML=a:void 0!=a&&d.appendChild(a);c&&(d.className=c);return d};
Template.prototype.createLink=Template.createLink=function(a,b,c){var d=document.createElement("a");d.href=b;b=typeof a;"string"==b||"number"==b?d.innerHTML=a:d.appendChild(a);c&&(d.className=c);return d};Template.prototype.createDiv=function(a,b){return this.createElement("div",a,b)};Template.prototype.createHeader=function(a,b){return this.createElement("h1",a,b)};Template.prototype.createSpan=function(a,b){return this.createElement("span",a,b)};
Template.prototype.createElement=Template.createElement=function(a,b,c){a=document.createElement(a);b&&(a.innerHTML=b);c&&(a.className=c);return a};Template.prototype.addBreak=function(a){var b=document.createElement("br");a.appendChild(b);return b};Template.prototype.addSpace=function(a){var b=document.createTextNode(" ");a.appendChild(b);return b};Template.prototype.addText=function(a,b){var c=document.createTextNode(b);a.appendChild(c);return c};
Template.prototype.addElem=Template.addElem=function(a,b,c,d){b=this.createElement(b,c,d);a.appendChild(b);return b};Template.prototype.addDiv=function(a,b,c){return this.addElem(a,"div",b,c)};Template.prototype.addSpan=function(a,b,c){return this.addElem(a,"span",b,c)};Template.prototype.addValue=function(a,b,c){return this.addElem(a,"em",b,c)};Template.prototype.addCaption=function(a,b,c){return this.addElem(a,"b",b,c)};
Template.prototype.addFootnote=function(a,b,c){return this.addElem(a,"em",b,c)};Template.prototype.addHeader=function(a,b,c){return this.addElem(a,"h1",b,c)};
Template.prototype.makeElementDraggable=function(a,b){$(b).mousedown(a,function(a){1==a.which&&(a.preventDefault(),a.data.pageX=a.pageX,a.data.pageY=a.pageY,$(document.body).mousemove(a.data,function(a){var b=a.data,c=b.body;c.css("top",(b.bodyTop=c.top+(a.pageY-b.pageY))+"px");c.css("left",(b.bodyLeft=c.left+(a.pageX-b.pageX))+"px")}))});$(document.body).mouseup(a,function(a){$(document.body).unbind("mousemove");a=a.data;var b=a.body;b.top=a.bodyTop;b.left=a.bodyLeft})};
Template.prototype.setFieldsMaxHeight=function(a){var b=$(window),c=a.body;a=a.fields;var d=c.height()-a.offsetHeight+15,d=b.height()-d;b.height()<c.height()?(a.style.height=d+"px",a.style.width=a.offsetWidth+25+"px"):a.style.maxHeight=d+"px"};Template.prototype.toText=function(a){if(void 0==a)return"";var b=typeof a;return"boolean"==b?a?"Yes":"No":"number"==b?this.toNumber(a):a};
Template.prototype.fromArray=function(a){if(void 0==a||0==a.length)return"";for(var b=a[0],c=1;c<a.length;c++)b+="\n"+a[c];return b};Template.prototype.fromArrayWithComma=function(a){if(void 0==a||0==a.length)return"";for(var b=a[0],c=1;c<a.length;c++)b+=", "+a[c];return b};Template.prototype.toArray=function(a){if(void 0==a||0==a.length)return[];a=a.split(this.REGEX_NEW_LINE);for(var b=0;b<a.length;b++)""==(a[b]=$.trim(a[b]))&&a.splice(b--,1);return a};
Template.prototype.round=function(a,b){var c=Math.pow(10,b);return Math.round(a*c)/c};Template.prototype.toCurrency=function(a){return void 0==a?"":this.toNumber(a,2)};Template.prototype.toPercent=function(a){return void 0==a?"":this.toNumber(this.round(100*a,2),2)};Template.prototype.toSeconds=function(a){return void 0==a?"":this.toNumber(this.round(a/1E3,3),3)};Template.prototype.toWhole=function(a){return void 0==a?"":this.toNumber(Math.round(a),0)};
Template.prototype.toNumber=function(a,b){x=(a+"").split(".");x1=x[0];x2=1<x.length?x[1]:"";if(void 0!=b)if(x2.length<b)for(;x2.length<b;)x2+="0";else x2.length>b&&(x2=x2.substr(0,b));0<x2.length&&(x2="."+x2);for(var c=/(\d+)(\d{3})/;c.test(x1);)x1=x1.replace(c,"$1,$2");return x1+x2};Template.prototype.toBool=function(a){return"T"==a?"Yes":"No"};Template.prototype.toDateTime=function(a){return void 0==a?"":(new Date(a)).toLocaleString()};Template.prototype.toDate=function(a){return void 0==a?"":(new Date(a)).toDateString()};
Template.prototype.toTime=function(a){return void 0==a?"":(new Date(a)).toTimeString()};Template.prototype.toSize=function(a){return a?this.KILO>a?this.toWhole(a)+" bytes":this.MEGA>a?this.toNumber(a/this.KILO,3)+" KB":this.GIGA>a?this.toNumber(a/this.MEGA,3)+" MB":this.toNumber(a/this.GIGA,3)+" GB":"N/A"};
Template.prototype.genInput=Template.genInput=function(a,b,c){if(document.all)return document.createElement('<input name="'+a+'" type="'+b+'"'+(c?" checked":"")+" />");var d=document.createElement("input");d.name=a;d.type=b;d.checked=c;d.setFieldStatus=function(a){this.disabled=!a;this.previousSibling.className=a?"":"disabled"};return d};Template.prototype.genButton=function(a,b,c){a=this.genInput(a,"button");b&&(a.value=b);c&&(a.onclick=c);return a};
Template.prototype.genCheckBox=function(a,b){return this.genInput(a,"checkbox",b)};Template.prototype.genCheckBoxes=function(a,b,c,d){d||(d=1);for(var e,g,h,k=this.createDiv(void 0,"multiselect"),l="column_"+d,m=0;m<b.length;m++){e=b[m];g=!1;if(c)for(var p=0;p<c.length&&!(g=e.id==c[p]);p++);0<m&&0==m%d&&this.addBreak(k);(h=this.addSpan(k,e.name,l)).insertBefore(g=this.genCheckBox(a,g),h.firstChild);g.value=e.id}return k};
Template.prototype.genFile=function(a,b,c){a=this.genInput(a,"file");b&&(a.maxLength=b);c&&(a.size=c);return a};Template.prototype.genHidden=Template.genHidden=function(a,b){var c=this.genInput(a,"hidden");void 0!=b&&(c.value=b);return c};Template.prototype.genPassword=function(a,b,c){a=this.genInput(a,"password");b&&(a.maxLength=b);c&&(a.size=c);return a};Template.prototype.genRadio=function(a,b,c){a=this.genInput(a,"radio",b);c&&(a.value=c);return a};
Template.prototype.genSelect=Template.genSelect=function(a,b,c,d){var e;document.all?e=document.createElement('<select name="'+a+'" />'):(e=document.createElement("select"),e.name=a);a=e.options;d&&(a[0]=new Option(d,""));if(b)for(d=0;d<b.length;d++){var g=b[d];a[a.length]=new Option(g.name,g.id)}c&&(e.value=c);e.setFieldStatus=function(a){this.disabled=!a;this.previousSibling.className=a?"":"disabled"};return e};
Template.prototype.repopulateList=Template.repopulateList=function(a,b,c,d){this.post(b,c,function(b){var c,h=a.options;h.length=0;d&&(h[h.length]=new Option(d,""));if(b&&0<b.length)for(var k=0;k<b.length;k++)h[h.length]=new Option((c=b[k]).name,c.id)})};Template.prototype.genSubmit=function(a,b){var c=this.genInput(a,"submit");b&&(c.value=b);return c};Template.prototype.genTextBox=function(a,b,c){a=this.genInput(a,"text");b&&(a.maxLength=b);c&&(a.size=c);return a};
Template.prototype.genTextArea=function(a,b,c,d){var e;document.all?e=document.createElement('<textarea name="'+a+'" />'):(e=document.createElement("textarea"),e.name=a);b&&(e.cols=b);c&&(e.rows=c);void 0!=d&&(e.value=d);e.setFieldStatus=function(a){this.disabled=!a;this.previousSibling.className=a?"":"disabled"};return e};Template.prototype.encodeHTML=Template.encodeHTML=function(a){if(!a)return a;for(var b,c="",d=a.length,e=0;e<d;e++)b=a.charCodeAt(e),c=255<b?c+("&#"+b+";"):c+a.charAt(e);return c};
Template.prototype.getLocation=Template.getLocation=function(a){return $(a).offset()};Template.prototype.getLocationBelow=Template.getLocationBelow=function(a){var b=(a=$(a)).offset();b.top+=a.outerHeight();return b};Template.prototype.getLocationRightBottom=Template.getLocationRightBottom=function(a){var b=(a=$(a)).offset();b.top+=a.outerHeight();b.right=b.left+a.outerWidth();return b};
Template.prototype.getLocationRightTop=Template.getLocationRightTop=function(a){var b=(a=$(a)).offset();b.right=b.left+a.outerWidth();b.bottom=b.top+a.outerHeight();return b};function TabTemplate(){}function Tab(a,b,c,d,e){this.id=a;this.caption=b;this.children=c;this.right=d;this.onlyAction=e}TabTemplate.prototype=new Template;TabTemplate.prototype.CSS_MAIN="tabber";TabTemplate.prototype.CSS_TABS="tabs";
TabTemplate.prototype.init=function(a){var b=this,c={anchors:[]},d,e,g,h,k=document.createElement("div");k.className=this.CSS_MAIN;k.appendChild(e=this.createElement("div",void 0,this.CSS_TABS));for(var l=0;l<this.TABS.length;l++)d=void 0,h=this.TABS[l],h.id&&(e.appendChild(d=c.anchors[l]=this.createAnchor(h.caption,function(a){b.handleAction(c,this)})),c[h.id]=d),h.children&&(d||e.appendChild(d=c.anchors[l]=this.createAnchor(h.caption,function(a){this.myInit&&(b.showTab(c,this),b.closeMenuNow(c,
this))})),d.onmouseover=function(a){b.openMenu(c,this)},d.onmouseout=function(a){b.closeMenuSoon(c,this)}),d.myIndex=l,d.myInit=!1,d.myTab=h,k.appendChild(g=document.createElement("div")),(d.myBody=$(g)).hide();h=c.currentTab=this.TABS[0];d=c.currentAnchor=c.anchors[0];(g=d.myBody).show();d.myInit=!0;d.className="selected";this[h.id](g);a.empty();a.append(k);return c};
TabTemplate.prototype.changeTab=function(a,b){var c=a.anchors;if(0>b||c.length<=b)throw"The INDEX is not valid.";c=c[b];this.handleAction(a,c);return c.myBody};TabTemplate.prototype.changeTabById=function(a,b){var c=a[b];if(!c)throw"The INDEX is not valid.";this.handleAction(a,c);return c.myBody};
TabTemplate.prototype.handleAction=function(a,b){var c=a.currentAnchor;c.myBody.hide();c.className="";var d=a.currentTab=b.myTab;a.currentAnchor=b;c.myIndex==b.myIndex&&(b.myInit=!1);b.className="selected";b.myBody.show();b.myInit||(b.myInit=!0,this[d.id](b.myBody))};TabTemplate.prototype.showTab=function(a,b){var c=a.currentAnchor;c.myBody.hide();c.className="";a.currentTab=b.myTab;a.currentAnchor=b;b.className="selected";b.myBody.show()};
TabTemplate.prototype.openMenu=function(a,b){b.mySubMenuCloseId&&(window.clearTimeout(b.mySubMenuCloseId),delete b.mySubMenuCloseId);if(!b.mySubMenu){var c=this,d=b.myTab,e,g=b.mySubMenu=document.createElement("div");g.className="tabberDropdown";(e=document.body).insertBefore(g,e.firstChild);for(var h,k=d.children,l=0;l<k.length;l++)h=k[l],g.appendChild(e=this.createAnchor(h.caption,function(d){if(this.myTab.onlyAction)c[this.myTab.id]();else c.showTab(a,b),c[this.myTab.id](b.myBody),b.myInit=!0;
c.closeMenuNow(a,b)})),e.onmouseover=function(a){b.mySubMenuCloseId&&(window.clearTimeout(b.mySubMenuCloseId),delete b.mySubMenuCloseId)},e.onmouseout=function(d){c.closeMenuSoon(a,b)},e.myTab=h;e=g.style;h=Template.getLocationBelow(b);e.top=h.top+"px";e.display="block";d.right&&(h.left-=g.clientWidth-b.clientWidth);e.left=h.left+"px"}};TabTemplate.prototype.closeMenuNow=function(a,b){document.body.removeChild(b.mySubMenu);delete b.mySubMenu};
TabTemplate.prototype.closeMenuSoon=function(a,b){b.mySubMenu&&(b.mySubMenuCloseId=window.setTimeout(function(){b.mySubMenu&&b.mySubMenuCloseId&&(document.body.removeChild(b.mySubMenu),delete b.mySubMenu,delete b.mySubMenuCloseId)},500))};function ListTemplate(a){this.load(a);if(this.CAN_EDIT||this.CAN_ADD)this.EDITOR=new EditTemplate(a);this.OPEN_CHILD=void 0!=this.openChild;this.HAS_ROW_ACTIONS=this.CAN_REMOVE||this.OPEN_CHILD||this.ROW_ACTIONS;this.IDENTIFIER||(this.IDENTIFIER="id");!this.DESC_COLS&&this.COLUMNS&&(a=this.COLUMNS.length,this.HAS_ROW_ACTIONS&&a++,a/=2,this.DESC_COLS=Math.ceil(a),this.NAV_COLS=Math.floor(a));this.SEARCH?(this.SEARCH_METHOD="post",this.SEARCH_PATH=this.RESOURCE+"/search",this.search=new EditTemplate(this.SEARCH),
this.search.handleSubmit=function(a,c){this.populate(a,c);a.isModal&&a.body.closeMe();a.callback(a.value)}):(this.SEARCH_METHOD="get",this.SEARCH_PATH=this.RESOURCE)}function TextColumn(a,b,c,d,e,g,h){this.id=a;this.caption=b;this.formatter=c?c:"toText";this.selectable=d;this.highlight=e;this.clickHandler=g;this.css=e?"highlight":h}function EditColumn(a,b,c){this.id=a;this.caption=b;this.formatter=c?c:"toText";this.editable=!0}
function RowAction(a,b,c,d){this.id=a;this.caption=b;this.css=c;this.condition=d}ListTemplate.prototype=new Template;ListTemplate.prototype.MAX_PAGES=500;ListTemplate.prototype.HALF_MAX_PAGES=250;ListTemplate.prototype.init=function(a){return this.filter({},a)};ListTemplate.prototype.filter=function(a,b,c){return this.run({filter:a,baseFilter:a,url:this.SEARCH_PATH,exclusions:c},b,this.SEARCH_METHOD)};
ListTemplate.prototype.getTitle=function(a){return a.parent?this.PARENT+" "+this.PLURAL+": "+a.parent.name:this.PLURAL};
ListTemplate.prototype.onPostLoad=function(a){if(a.isModal){var b=$(window),c=a.body;if(c.height()>b.height()){for(var d=a.tbody,e=d.rows,g=e[0].cells,h=[],k=0;k<g.length;k++)g[k].style.width=(h[k]=g[k].clientWidth)+"px";for(k=1;k<e.length;k++)for(var g=e[k].cells,l=0;l<h.length;l++)g[l].style.width=h[l]+"px";k=c.height()-d.offsetHeight+25;d.style.height=b.height()-k+"px";d.className=this.CSS_MODAL;a.table.style.display="inline";b=a.thead.rows[1].cells;for(k=0;k<h.length;k++)b[k].style.width=h[k]+
"px"}}if(this.onListPostLoad)this.onListPostLoad(a)};ListTemplate.prototype.handleCancel=function(a){a.isModal&&a.body.closeMe()};ListTemplate.prototype.doPaging=function(a,b){a.filter.page=b.nextPage;this.run(a)};ListTemplate.prototype.doSort=function(a,b){var c=a.filter,d=a.value;c.sortOn=b.sortOn;d.sortOn==c.sortOn?c.sortDir="ASC"==d.sortDir?"DESC":"ASC":delete c.sortDir;this.run(a)};
ListTemplate.prototype.generate=function(a){var b=a.value;$.isArray(b)&&(a.value=b={total:b.length,pageSize:b.length,page:1,pages:1,records:b});b=b.records;if(!b||0==b.length)return this.createNoRecordsFoundMessage(a);b=a.table=document.createElement("table");this.appendHeader(a,b);this.appendBody(a,b);return b};
ListTemplate.prototype.createNoRecordsFoundMessage=function(a){var b=a.value,b=this.createDiv(b.message?b.message:"No "+this.PLURAL+" found.","noRecordsFound"),c=this;this.CAN_ADD&&b.appendChild(this.createAnchor("Click here to add a new "+this.SINGULAR+".",function(b){c.handleAdd(a,this)}));this.search&&b.appendChild(this.createAnchor("Click here to apply a different search.",function(b){c.handleSearch(a,this)}));return b};
ListTemplate.prototype.appendHeader=function(a,b){var c,d=a.thead=b.createTHead(),e,g=this.COLUMNS;this.insertPaging(b,d,a);c=this.insertRow(d);this.HAS_ROW_ACTIONS&&c.insertCell(0);for(var h=$.extend({},a.exclusions),k=0;k<g.length;k++)e=g[k],h[e.id]||this.insertHeader(c,e.id,e.caption,a);return d};
ListTemplate.prototype.appendBody=function(a,b){var c,d,e=this.COLUMNS,g,h=a.value.records,k,l,m,p=a.tbody=document.createElement("tbody");b.appendChild(p);for(var n=this,q=$.extend({},a.exclusions),r=0;r<h.length;r++){g=h[r];m=this.insertRow(p);this.HAS_ROW_ACTIONS&&(k=this.addDiv(this.insertCell(m),void 0,"rowActions"),this.CAN_REMOVE&&(k.appendChild(c=this.createAnchor("&chi;",function(b){n.removeRecord(a,this)},"delete")),c.myRecord=g),this.addSpace(k),this.OPEN_CHILD&&(k.appendChild(c=this.createAnchor("&crarr;",
function(b){n.openChild(a,this)},"drilldown")),c.myRecord=g,this.decorateOpenChildAnchor(c,g)),this.addSpace(k),this.HAS_HISTORY&&(k.appendChild(c=this.createAnchor(void 0,function(a){n.HISTORY_VIEWER.open(this.myRecord)},"history","History")),c.myRecord=g),this.ROW_ACTIONS&&(k.appendChild(c=this.createAnchor(void 0,function(a){return!1},"config")),c.myRecord=g,c.onmouseover=function(b){n.openActionsMenu(a,this)},c.onmouseout=function(b){n.closeActionsMenuSoon(a,this)}));for(var t=0;t<e.length;t++)d=
e[t],q[d.id]||(c=this[d.formatter](l=g[d.id]),k=void 0,d.selectable?k="handleSelect":d.clickHandler&&(k=d.clickHandler),k?(d=this.insertCell(m,d.css,c=this.createAnchor(c,function(b){n[this.myOnSelect](a,this)})),c.myOnSelect=k,c.myRecord=g):this.CAN_EDIT&&void 0!=l&&"boolean"==typeof l?(d=this.insertCell(m,d.css,k=this.genCheckBox(d.id,l)),d.className+=" center",k.onclick=function(b){n.toggleProperty(a,this)},k.myRecord=g):d.editable?$(this.insertCell(m,d.css,c)).dblclick({c:a,r:g,f:d,t:c},function(a){if(!(1<
a.which)){a.preventDefault();var b=a.data;a=a.target;var c=n.genTextBox(b.f.id),d=b.r[b.f.id];c.style.width=a.clientWidth-16+"px";c.value=d?d:"";a.innerHTML="";a.appendChild(c);c.focus();b.cell=a;$(c).blur(b,function(a){a.target.cancelBlur||(a.data.cell.innerHTML=a.data.t)}).change(b,function(a){a.target.cancelBlur=!0;n.updateField(a.data,a.target)})}}):this.insertCell(m,d.css,c))}return p};
ListTemplate.prototype.openActionsMenu=function(a,b){this.clearMenuClose(b);if(!b.myMenu){var c=this,d=b.myRecord,e,g,h=b.myMenu=document.createElement("div");h.className="tabberDropdown";(e=document.body).insertBefore(h,e.firstChild);for(var k=0;k<this.ROW_ACTIONS.length;k++)if(g=this.ROW_ACTIONS[k],!g.condition||d[g.condition])h.appendChild(e=this.createAnchor(g.caption,function(d){c[this.myId](a,this);c.closeActionsMenu(a,b)})),e.myRecord=d,e.myId=g.id,e.onmouseover=function(a){c.clearMenuClose(b)},
e.onmouseout=function(d){c.closeActionsMenuSoon(a,b)};d=h.style;e=this.getLocationRightTop(b);d.display="block";g=$(window);g.height()/2<e.top-g.scrollTop()?(h=e.bottom-$(h).outerHeight(),h<g.scrollTop()&&(h=g.scrollTop()),d.top=h+"px"):(h=e.top+$(h).outerHeight(),h>g.height()+g.scrollTop()&&(e.top-=h-(g.height()+g.scrollTop())),d.top=e.top+"px");d.left=e.right+"px"}};ListTemplate.prototype.clearMenuClose=function(a){a.myMenuCloseId&&(window.clearTimeout(a.myMenuCloseId),delete a.myMenuCloseId)};
ListTemplate.prototype.closeActionsMenu=function(a,b){document.body.removeChild(b.myMenu);delete b.myMenu};ListTemplate.prototype.closeActionsMenuSoon=function(a,b){b.myMenu&&(b.myMenuCloseId=window.setTimeout(function(){b.myMenu&&b.myMenuCloseId&&(document.body.removeChild(b.myMenu),delete b.myMenu,delete b.myMenuCloseId)},500))};ListTemplate.prototype.insertRow=function(a){a=a.insertRow(a.rows.length);a.className=0==a.rowIndex%2?"even":"odd";return a};
ListTemplate.prototype.insertPaging=function(a,b,c){this.insertPaging_(b,c);this.insertPaging_(c.tfoot=a.createTFoot(),c)};
ListTemplate.prototype.insertPaging_=function(a,b){var c=this,d=b.value,e=this.insertRow(a),g=e.insertCell(0);g.colSpan=this.DESC_COLS;if(1==d.total)g.innerHTML="Showing only "+this.SINGULAR;else{var h=d.records.length;g.innerHTML=1==h?"Showing one "+this.SINGULAR:"Showing "+h+" "+this.PLURAL;g.innerHTML+=" out of "+d.total}this.CAN_ADD&&g.appendChild(this.createAnchor("Add Item",function(a){c.handleAdd(b,this)},"action"));this.search&&g.appendChild(this.createAnchor("Search",function(a){c.handleSearch(b,
this)},"action"));if(this.ACTIONS)for(h=0;h<this.ACTIONS.length;h++){var k,l=this.ACTIONS[h];g.appendChild(k=this.createAnchor(l.caption,function(a){c[this.myId](b,this)},"action"));k.myId=l.id}g=e.insertCell(1);g.colSpan=this.NAV_COLS;g.className="right";if(!(2>d.pages)){1<d.page&&(g.appendChild(e=this.createAnchor("&lArr; prev",function(a){c.doPaging(b,this)})),e.nextPage=d.page-1,g.appendChild(document.createTextNode(" ")));h=1;k=d.pages;this.MAX_PAGES<d.pages&&(this.HALF_MAX_PAGES<d.page&&(h=
d.page-this.HALF_MAX_PAGES),k=h+this.MAX_PAGES,k>d.pages&&(k=d.pages,h=k-this.MAX_PAGES));g.appendChild(e=document.createElement("select"));l=0;for(1<h&&(e.options[l++]=new Option(1,1,!1,1==d.page));h<=k;h++,l++)e.options[l]=new Option(h,h,!1,h==d.page);d.pages>k&&(e.options[l++]=new Option(d.pages,d.pages,!1,d.pages==d.page));e.onchange=function(a){this.nextPage=this.value;c.doPaging(b,this)};d.pages>d.page&&(g.appendChild(document.createTextNode(" ")),g.appendChild(e=this.createAnchor("next &rArr;",
function(a){c.doPaging(b,this)})),e.nextPage=d.page+1)}};ListTemplate.prototype.insertHeader=function(a,b,c,d){var e=this;a=a.insertCell(a.cells.length);a.appendChild(c=this.createAnchor(c,function(a){e.doSort(d,this)}));c.sortOn=b;c=d.value;b==c.sortOn&&a.appendChild(this.createSpan(" "+("ASC"==c.sortDir?"&uarr;":"&darr;")));return a};
ListTemplate.prototype.insertCell=function(a,b,c){var d=a.insertCell(a.cells.length);d.className=b?b:a.className;void 0!=c&&("string"==typeof c?d.innerHTML=c:d.appendChild(c));return d};ListTemplate.prototype.decorateOpenChildAnchor=function(a,b){if(void 0!=b.numberOfChildren)this.addSpan(a," ("+this.toWhole(b.numberOfChildren)+")");else{var c=this;this.COUNT_CHILDREN_URL&&Template.post(this.COUNT_CHILDREN_URL,{id:b.id},function(b){c.addSpan(a," ("+c.toWhole(b)+")")})}};
ListTemplate.prototype.handleAdd=function(a,b){var c=this;this.EDITOR.doAdd(function(b){c.run(a,void 0,c.SEARCH_METHOD)},this.NO_EDITOR_MODAL?a.body:void 0)};ListTemplate.prototype.handleSelect=function(a,b){var c=this;this.EDITOR.doEdit(b.myRecord[this.IDENTIFIER],function(b){c.run(a,void 0,c.SEARCH_METHOD)},this.NO_EDITOR_MODAL?a.body:void 0)};
ListTemplate.prototype.handleSearch=function(a,b){var c=this;this.search.doSearch(function(b){b&&(a.filter=b);c.run(a)},this.NO_SEARCH_MODAL?a.body:void 0,a.baseFilter)};ListTemplate.prototype.removeRecord=function(a,b){if(window.confirm("Click OK to confirm and continue with your delete.")){var c=this;this.remove(this.RESOURCE,b.myRecord.id,function(b){b.isError?window.alert(b.message):c.run(a)})}};
ListTemplate.prototype.updateField=function(a,b){var c=a.r,d=a.f;c[d.id]=b.value;this.put(this.POST_URL,this.toRecord(c),function(c){if(c.isError)c[d.id]?window.alert(d.caption+" "+c[d.id]):window.alert("An unexpected error occurred. Please contact the administrator."),b.focus(),b.cancelBlur=!1;else{var g=b.parentNode;g.innerHTML=a.t=b.value;var h=g.style.backgroundColor;g.style.backgroundColor="red";setTimeout(function(){g.style.backgroundColor=h},500)}})};
ListTemplate.prototype.toggleProperty=function(a,b){var c=b.myRecord;c[b.name]=b.checked;this.post(this.RESOURCE,c,function(a){if(a.isError)a[b.name]?window.alert(f.caption+" "+a[b.name]):window.alert("An unexpected error occurred. Please contact the administrator."),c[b.name]=b.checked=!b.checked;else{var e=b.parentNode,g=e.style.backgroundColor;e.style.backgroundColor="red";setTimeout(function(){e.style.backgroundColor=g},500)}})};function EditTemplate(a){this.load(a)}function TextField(a,b,c,d,e){this.isText=!0;this.isEditable=!1;this.id=a;this.caption=b;this.footnote=d;this.includeOnAdds=e;c?"function"==typeof c?this.custom=c:this.formatter=c:this.formatter="toText"}function BoolField(a,b,c,d){this.isEditable=this.isBoolean=!0;this.id=a;this.caption=b;this.isRequired=c;this.footnote=d}
function EditField(a,b,c,d,e,g,h){this.isEditable=!0;this.id=a;this.caption=b;this.isRequired=c;this.isLong=d;this.maxLength=e;this.size=g;this.footnote=h}function HideField(a){this.isHidden=!0;this.id=a}function MultiField(a,b,c,d,e,g){this.isMulti=this.isEditable=!0;this.id=a;this.caption=b;this.isRequired=c;this.isLong=!0;this.maxLength=d;this.size=e;this.footnote=g}
function RangeField(a,b,c,d,e,g){this.isEditable=this.isRange=!0;this.id=a;this.caption=b;this.isRequired=c;this.maxLength=d;this.size=e;this.footnote=g}function ListField(a,b,c,d,e,g){this.isEditable=this.isSelectable=!0;this.id=a;this.caption=b;this.isRequired=c;this.options=d;this.footnote=e;this.header=g}function PickField(a,b,c,d,e,g){this.isEditable=this.isPickable=!0;this.id=a;this.caption=b;this.isRequired=c;this.options=d;this.columns=e;this.footnote=g}
function DateField(a,b,c,d){this.isEditable=this.isDate=!0;this.id=a;this.caption=b;this.isRequired=c;this.doSelect=d}function DatesField(a,b,c,d){this.isEditable=this.isDateRange=!0;this.id=a;this.caption=b;this.isRequired=c;this.doSelect=d}function TimeField(a,b,c,d){this.isEditable=this.isTime=!0;this.id=a;this.caption=b;this.isRequired=c;this.doSelect=d}function StampField(a,b,c,d){this.isEditable=this.isTimestamp=!0;this.id=a;this.caption=b;this.isRequired=c;this.doSelect=d}
function DropField(a,b,c,d,e,g){this.isEditable=this.isDropdownList=!0;this.id=a;this.caption=b;this.isRequired=c;this.doFill="function"==typeof d?d:function(a){Template.get(d+"/find",{name:a.field.value},function(b){a.caller.fill(a,b)})};this.doSelect="function"==typeof e?e:function(a){var b=a.selection;a.extra.texts[e].innerHTML=b?b.name+" ("+b.id+")":"Cleared"};this.footnote=g}
function TagField(a,b,c,d,e,g,h){this.isEditable=this.isWidget=this.isTagger=!0;this.widget=DropdownTagger;this.id=a;this.caption=b;this.isRequired=c;this.doFill="function"==typeof d?d:function(a){Template.get(d+"/find",{name:a.field.value},function(b){a.caller.fill(a,b)})};this.doPostSelect=e;this.footnote=g;this.addCallback=h}
function MediaTagField(a,b,c,d,e,g,h){this.isEditable=this.isWidget=this.isTagger=!0;this.widget=MediaDropdownTagger;this.id=a;this.caption=b;this.isRequired=c;this.doFill="function"==typeof d?d:function(a){Template.get(d,{name:a.field.value},function(b){a.caller.fill(a,b)})};this.doPostSelect=e;this.footnote=g;this.addCallback=h}function PassField(a,b,c,d,e){this.isEditable=this.isPassword=!0;this.id=a;this.caption=b;this.isRequired=c;this.maxLength=d;this.size=e}
function FileField(a,b,c){this.isEditable=this.isFile=!0;this.id=a;this.caption=b;this.isRequired=c}EditTemplate.prototype=new Template;EditTemplate.prototype.doAdd=function(a,b,c){this.run({value:void 0!=c?c:{active:!0},filter:{isAdd:!0},callback:a},b)};EditTemplate.prototype.doEdit=function(a,b,c){this.run({callback:b,url:this.RESOURCE+"/"+a},c,"get")};EditTemplate.prototype.doSearch=function(a,b,c){this.run({value:{},filter:$.extend({isSearch:!0,isAdd:!1,pageSize:20},c),callback:a},b)};
EditTemplate.prototype.ADD_METHOD="post";EditTemplate.prototype.EDIT_METHOD="post";EditTemplate.prototype.getTitle=function(a){var b=a.filter;void 0==b&&(b={});b=b.isSearch?"Search "+this.PLURAL:(b.isAdd?"Add":"Edit")+" "+this.SINGULAR;if(a=a.parent)b+=": "+a.name;return b};EditTemplate.prototype.onPostLoad=function(a){a.isModal&&this.setFieldsMaxHeight(a);a.firstField&&a.firstField.focus();if(this.onEditorPostLoad)this.onEditorPostLoad(a)};
EditTemplate.prototype.handleCancel=function(a){a.isModal?a.body.closeMe():a.callback()};EditTemplate.prototype.handleSubmit=function(a,b){this.populate(a,b);if(a.filter.isSearch)a.callback(a.value,a);else{var c=this;this[a.filter.isAdd?this.ADD_METHOD:this.EDIT_METHOD](this.RESOURCE,a.value,function(d){c.processResponse(d,a,b)})}};
EditTemplate.prototype.processResponse=function(a,b,c){if(a.isError){var d;if((b=a.errors)&&0<b.length)for(var e=0;e<b.length&&void 0==(d=c.elements[b[e].name]);e++);window.alert(a.message);d&&d.focus()}else b.isModal&&b.body.closeMe(),(c=b.callback)&&c(a,b)};
EditTemplate.prototype.populate=function(a,b){for(var c=a.value,d=0;d<this.FIELDS.length;d++){var e=this.FIELDS[d];if(e.isEditable||e.isHidden){var g=e.id;if(e.isRange||e.isDateRange)c[g+"From"]=b.elements[g+"From"].value,c[g+"To"]=b.elements[g+"To"].value;else{var h=b.elements[g];if(h)if(e.isPickable){for(var e=[],k=0;k<h.length;k++)h[k].checked&&(e[e.length]=h[k].value);0<e.length?c[g]=e:delete c[g]}else"checkbox"==h.type?c[g]=h.checked:e.isMulti?c[g]=this.toArray(h.value):e.isLong?c[g]=this.encodeHTML(h.value):
e.isTagger?c[g]=e.widget.retrieve(a.texts[g]).selectedIds:e.isDate||e.isTime||e.isTimestamp?""!=h.value&&(c[g]=parseInt(h.value)):c[g]=h.value}}}this.clean(c)};
EditTemplate.prototype.generate=function(a){var b=this,c=a.isModal,d,e=a.form=this.createElement("form"),g=a.filter;void 0==g&&(a.filter=g={});var h=g.isSearch?g:a.value,k,l,m=g.isAdd;e.className=this.NAME;this.FILE_UPLOAD?(e.appendChild(this.genHidden("id",h.id)),e.enctype="multipart/form-data",e.target="httpRPC",e.action=this.POST_URL,e.method="POST",d=$("#httpRPC"),d.unbind("load"),$("#httpRPC").load(function(c){b.processResponse(eval("("+c.target.contentWindow.document.body.innerHTML+")"),a,e)})):
e.onsubmit=function(c){try{b.handleSubmit(a,this)}catch(d){window.console&&console.log(d)}finally{return!1}};c||(a.header=this.addHeader(e,g.isSearch?"Search "+this.PLURAL:(m?"Add":"Edit")+" "+this.SINGULAR));for(var p=a.texts={},n=a.fields=this.addDiv(e,void 0,this.CSS_FIELDS),q=0;q<this.FIELDS.length;q++)k=this.FIELDS[q],m&&k.isText&&!k.includeOnAdds||(g=k.id,l=h[g],k.isHidden?e.appendChild(this.genHidden(g,l)):(c=this.addDiv(n),d=this.addCaption(c,k.caption+(k.isRequired?"*":"")),k.footnote&&this.addFootnote(d,
k.footnote),d=void 0,k.isText?p[g]=k.custom?this.addValue(c,k.custom(h,l,this)):this.addValue(c,this[k.formatter](l)):k.isSelectable?c.appendChild(d=this.genSelect(g,this.getList(k.options),l,k.header)):k.isDropdownList?c.appendChild(DropdownList.create(g,k,l,a)):k.isBoolean?c.appendChild(this.genCheckBox(g,l)):k.isDate?c.appendChild(DatePicker.create(g,l,a,k)):k.isTime?c.appendChild(TimePicker.create(g,l,a,k)):k.isTimestamp?c.appendChild(TimestampPicker.create(g,l,a,k)):k.isDateRange?(c.appendChild(DatePicker.create(g+
"From",void 0,a,k)),this.addText(c," to "),c.appendChild(DatePicker.create(g+"To",void 0,a,k))):k.isRange?(c.appendChild(d=this.genTextBox(g+"From",k.maxLength,k.size)),this.addText(c," to "),c.appendChild(this.genTextBox(g+"To",k.maxLength,k.size))):k.isPassword?c.appendChild(d=this.genPassword(g,k.maxLength,k.size)):k.isPickable?c.appendChild(this.genCheckBoxes(g,this.getList(k.options),l,k.columns)):k.isTagger?(c.appendChild(d=k.widget.create(g,k,l,a)),p[g]=d=d.myCriteria,d=d.field):k.isFile?c.appendChild(d=
this.genFile(g,128,50)):(k.isLong?c.appendChild(d=this.genTextArea(g,k.maxLength?k.maxLength:40,k.size?k.size:4)):c.appendChild(d=this.genTextBox(g,k.maxLength,k.size)),k.isMulti&&(l=this.fromArray(l)),void 0!=l&&(d.value=l)),d&&!a.firstField&&(a.firstField=d)));c=a.actions=this.addDiv(e,void 0,this.CSS_ACTIONS);c.appendChild(this.genSubmit("submitter","Submit"));this.addSpace(c);c.appendChild(this.genButton("canceler","Cancel",function(c){b.handleCancel(a)}));return e};function ViewTemplate(a){this.load(a)}ViewTemplate.prototype=new Template;ViewTemplate.prototype.getTitle=function(a){return SINGULAR};ViewTemplate.prototype.open=function(a,b,c){void 0==c&&(c=this.GET_URL);this.run({filter:a,url:c},b,"get")};ViewTemplate.prototype.openById=function(a,b,c){this.open(b,c,this.GET_URL+a)};ViewTemplate.prototype.onPostLoad=function(a){a.isModal&&(a.body.center(),a.header.style.width=a.form.offsetWidth+"px");if(this.onViewerPostLoad)this.onViewerPostLoad(a)};
ViewTemplate.prototype.handleClose=function(a){a.isModal&&a.body.closeMe()};ViewTemplate.prototype.generate=function(a){var b=this,c=a.isModal,d,e=a.form=this.createElement("form");e.className=this.NAME;d=a.header=this.addHeader(e,this.getTitle(a));c&&(d.appendChild(this.createAnchor("X",function(c){b.handleClose(a)})),this.makeElementDraggable(a,d));this.append(a,e);this.addDiv(e,void 0,"close").appendChild(this.genButton("closer","Close",function(c){b.handleClose(a)}));return e};
ViewTemplate.prototype.append=function(a,b){var c,d=a.value;c=this.addDiv(b);this.addCaption(c).appendChild(this.createImg(d.image_src,d.title));this.addSpan(c,d.contents);d.is_available?d.contact_name&&(c=this.addDiv(b,"For more information, please contact ","contact"),c.appendChild(this.createLink(d.contact_name,"mailto:"+d.contact_email+"?subject=Regarding "+d.name))):this.addDiv(b,"Thank you for your interest, but I have already been adopted!","contact")};var ProgressBar={INTERVAL:2E3,ITERATIONS:20,CAPTION:"Loading ...",start:function(a){var b=this,c=a.progressBarBody=$("<blockquote>");a.body.empty();a.body.append(c);c.html(a.progressBarLastCaption=this.CAPTION);a.progressBarInterval=1;a.progressBarIntervalId=window.setInterval(function(){b.ITERATIONS<a.progressBarInterval++?b.stop(a):c.html(a.progressBarLastCaption+=".")},this.INTERVAL)},stop:function(a){a.progressBarIntervalId&&(window.clearInterval(a.progressBarIntervalId),a.progressBarIntervalId=
void 0)}};var KEY_NULL=0,KEY_BACKSPACE=8,KEY_TAB=9,KEY_ENTER=13,KEY_ESCAPE=27,KEY_SPACE=32,KEY_PAGE_UP=33,KEY_PAGE_DOWN=34,KEY_END=35,KEY_HOME=36,KEY_LEFT=37,KEY_UP=38,KEY_RIGHT=39,KEY_DOWN=40,KEY_PAREN_OPEN=40,KEY_PAREN_CLOSED=41,KEY_PLUS=43,KEY_HYPHEN=45,KEY_ZERO=48,KEY_NINE=57,KEY_COLON=58;var DropdownList={CSS_MAIN:"dropdownList",CSS_HOVER:"hover",DELAY:500,SUFFIX:"_ddl",create:function(a,b,c,d){var e=this,g=document.createElement("span"),h=g.myCriteria={name:a,callback:b,value:c,closed:!0,caller:this,extra:d};g.appendChild(h.hidden=this.genInput(a,"hidden"));void 0!=c&&(h.hidden.value=c);g.appendChild(a=h.field=this.genInput(a+this.SUFFIX,"text"));g.appendChild(this.createAnchor("X",function(a){e.reset(h)},this.CSS_MAIN));g.appendChild(b=h.div=document.createElement("div"));g.className=
a.className=b.className=this.CSS_MAIN;a.setAttribute("autocomplete","off");$(a).keyup(h,function(a){var b=a.data;b.lastTimeoutId&&(window.clearTimeout(b.lastTimeoutId),delete b.lastTimeoutId);var c=a.which;""==a.target.value||KEY_ESCAPE==c||KEY_TAB==c?e.close(b):KEY_DOWN==c?e.moveDown(b,1):KEY_UP==c?e.moveUp(b,1):KEY_PAGE_DOWN==c?e.moveDown(b,10):KEY_PAGE_UP==c?e.moveUp(b,10):KEY_HOME==c?e.moveTo(b,0):KEY_END==c?e.moveTo(b,b.lastIndex):KEY_ENTER!=c&&(b.lastTimeoutId=window.setTimeout(function(){delete b.lastTimeoutId;
b.callback.doFill(b)},e.DELAY))}).keydown(h,function(a){var b=a.data;KEY_ENTER!=a.which||b.closed||(e.select(b),a.preventDefault())});return g},fill:function(a,b){var c=this,d,e=a.div;e.innerHTML="";a.anchors=[];for(var g=0;g<b.length;g++){var h=b[g];e.appendChild(d=a.anchors[g]=document.createElement("a"));d.href="javascript:void(null)";d.innerHTML=this.toCaption(h);d.myIndex=g;d.myItem=h;d.onclick=function(b){c.handleSelect(a,this)}}this.open(a);e.scrollTop=0;a.lastIndex=b.length-1;0<b.length?a.anchors[a.index=
0].className=this.CSS_HOVER:a.index=void 0},handleSelect:function(a,b){var c=a.selection=b.myItem;a.index=b.myIndex;a.hidden.value=c.id;a.field.value=c.name;this.close(a);c=a.callback;c.doSelect&&c.doSelect(a)},reset:function(a){delete a.selection;a.hidden.value="";a.field.value="";var b=a.callback;b.doSelect&&b.doSelect(a)},open:function(a){a.closed&&(a.closed=!1,a.div.style.display="block")},close:function(a){a.closed||(a.closed=!0,a.div.style.display="none")},select:function(a){void 0!=a.index&&
this.handleSelect(a,a.anchors[a.index])},moveUp:function(a,b){if(void 0!=a.index){var c=a.index-b;0>c&&(c=0);this.moveTo(a,c)}},moveDown:function(a,b){if(void 0!=a.index){var c=a.index+b;a.lastIndex<c&&(c=a.lastIndex);this.moveTo(a,c)}},moveTo:function(a,b){if(void 0!=a.index){a.anchors[a.index].className="";var c,d=a.div;(c=a.anchors[a.index=b]).className=this.CSS_HOVER;if(c.offsetTop<d.scrollTop||c.offsetTop+c.offsetHeight>d.scrollTop+d.clientHeight)d.scrollTop=c.offsetTop;this.open(a)}},clear:function(a,
b){var c;if(c=a.elements[b])c.value="";if(c=a.elements[b+this.SUFFIX])c.value=""},enable:function(a,b){var c;(c=a.elements[b])&&c.setFieldStatus(!0);if(c=a.elements[b+this.SUFFIX])c.disabled=!1},disable:function(a,b){var c;if(c=a.elements[b])c.value="",c.setFieldStatus(!1);if(c=a.elements[b+this.SUFFIX])c.value="",c.disabled=!0},focus:function(a,b){var c;(c=a.elements[b+this.SUFFIX])&&c.focus()}};DropdownList.genInput=Template.prototype.genInput;DropdownList.createAnchor=Template.prototype.createAnchor;
DropdownList.toCaption=function(a){return a.name+" ("+a.id+")"};var DatePicker={CSS_MAIN:"datePicker",SUFFIX:"_date",DAYS:"Su M Tu W Th F Sa".split(" "),MONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),create:function(a,b,c,d){var e,g=document.createElement("span"),h={name:a,value:b,closed:!0,caller:this,extra:c,callback:d};g.appendChild(e=h.hidden=this.genInput(a,"hidden"));g.appendChild(a=h.field=this.genInput(a+this.SUFFIX,"text"));g.appendChild(c=h.div=document.createElement("div"));g.className=a.className=c.className=this.CSS_MAIN;a.setAttribute("autocomplete",
"off");void 0!=b&&(e.value=(new Date(b)).getTime(),a.value=this.toInputDate(b));var k=this;a.onchange=function(a){if(""==this.value)return e.value="",h.value=void 0,!0;try{k.select(h,k.parseInputDate(this.value))}catch(b){return window.alert(b),!1}return!0};a.onfocus=function(a){k.open(h)};a.onblur=function(a){k.scheduleClose(h)};return g},open:function(a,b){this.cancelClose(a);var c=this,d,e,g=a.div;b||(b=void 0!=a.value?this.parseDbDate(a.value):new Date);var h,k=1,l=b.getMonth();b.setDate(k);b.clone=
function(){return new Date(this.getTime())};g.innerHTML="";g.appendChild(e=document.createElement("ul"));e.className="header";this.addFlippers(e,this.MONTHS[l],a,b,"Month");this.addFlippers(e,b.getFullYear(),a,b,"FullYear");g.appendChild(e=document.createElement("ul"));e.className="caption";for(h=0;h<this.DAYS.length;h++)e.appendChild(d=document.createElement("li")),d.innerHTML=this.DAYS[h];g.appendChild(e=document.createElement("ul"));e.className="detail";e.appendChild(d=document.createElement("li"));
d.className="buffer"+b.getDay();d.innerHTML="&nbsp;";e.appendChild(d=document.createElement("li"));this.addAnchor(d,k,function(b){c.select(a,this.myValue);return!1},b.clone());b.setDate(++k);do h=b.getDay(),0==h&&(g.appendChild(e=document.createElement("ul")),e.className="detail"),e.appendChild(d=document.createElement("li")),this.addAnchor(d,k,function(b){c.select(a,this.myValue);return!1},b.clone()),b.setDate(++k);while(l==b.getMonth());e.appendChild(d=document.createElement("li"));d.className=
"buffer"+(6-h);d.innerHTML="&nbsp;";g.appendChild(e=document.createElement("ul"));e.className="footer";e.appendChild(d=document.createElement("li"));this.addAnchor(d,"Close",function(b){c.close(a);return!1});a.closed=!1;g.style.display="block"},select:function(a,b){a.hidden.value=a.value=this.toDbDate(b);a.field.value=this.toInputDate_(b);var c=a.callback;c&&c.doSelect&&c.doSelect(a,b);this.close(a)},close:function(a){delete a.scheduleCloseId;a.closed=!0;a.div.style.display="none"},scheduleClose:function(a){if(!a.scheduleCloseId){var b=
this;a.scheduleCloseId=setTimeout(function(){b.close(a)},1E3)}},cancelClose:function(a){a.scheduleCloseId&&(clearTimeout(a.scheduleCloseId),delete a.scheduleCloseId)}};DatePicker.genInput=Template.prototype.genInput;DatePicker.createAnchor=Template.prototype.createAnchor;DatePicker.addAnchor=function(a,b,c,d){b=this.createAnchor(b,c);b.myValue=d;a.appendChild(b);return b};
DatePicker.addFlipper=function(a,b,c,d,e,g){var h=this;this.addAnchor(a,b,function(a){a=this.myValue;a["set"+e](a["get"+e]()+g);h.open(c,a);return!1},d.clone())};DatePicker.addFlippers=function(a,b,c,d,e){var g=document.createElement("li");a.appendChild(g);this.addFlipper(g,"&lt;",c,d,e,-1);g.appendChild(document.createTextNode(b));this.addFlipper(g,"&gt;",c,d,e,1)};DatePicker.toInputDate=function(a){return this.toInputDate_(this.parseDbDate(a))};
DatePicker.toInputDate_=function(a){return a.getMonth()+1+"/"+a.getDate()+"/"+a.getFullYear()};DatePicker.toDbDate=function(a){return a.getFullYear()+"-"+this.padInt(a.getMonth()+1)+"-"+this.padInt(a.getDate())+"T00:00:00+0000"};DatePicker.padInt=function(a){return 10>a?"0"+a:a};
DatePicker.parseInputDate=function(a){var b,c;a=a.split("/",3);if(2>a.length)throw"Invalid input date: must contain at least 2 parts separated by a backslash.";if(isNaN(b=parseInt(a[0])))throw"Invalid input date: the month ("+a[0]+") is not a number";if(1>b||12<b)throw"Invalid input date: the month ("+a[0]+") is not between 1 and 12.";if(isNaN(c=parseInt(a[1])))throw"Invalid input date: the date ("+a[1]+") is not a number";if(1>c||31<c)throw"Invalid input date: the date ("+a[1]+") is not between 1 and 31.";
var d=new Date;d.setHours(0,0,0,0);d.setMonth(b-1,c);if(2<a.length){if(isNaN(b=parseInt(a[2])))throw"Invalid input date: the year ("+a[2]+") is not a number";if(0>b)throw"Invalid input date: the year ("+a[2]+") has to be a positive number.";50>b?b+=2E3:100>b&&(b+=1900);d.setFullYear(b)}return d};DatePicker.parseDbDate=function(a){a=new Date(a);a.setHours(0,0,0,0);return a};
DatePicker.removeZeroPadding=function(a){if(""==a)return a;for(var b=0;b<a.length&&"0"==a.charAt(b);b++);0<b&&a.length>b&&(a=a.substr(b));return a};var META_LOGIN={NAME:"login",POST_URL:"/login",LOGOUT_URL:"/logout",GET_LOGIN_INFO_URL:"/loginInfo",SINGULAR:"Login",PLURAL:"Login",FIELDS:[new EditField("userName","User Name",!0,!1,50,30),new PassField("password","Password",!0,50,30)],onEditorPostLoad:function(a){a=a.header;var b=a.lastChild;a.innerHTML="Login";a.appendChild(b)},doLogin:function(a,b){var c=this;this.run({filter:{isSearch:!0},value:{value:{}},callback:function(){c.anchorUp();a&&a()}},b,"get")},doLogout:function(){var a=this;this.post(this.LOGOUT_URL,
{},function(b){a.anchorUp()})},doStart:function(){this.ANCHOR=document.getElementById("loginLink");this.LOGIN_INFO=document.getElementById("loginInfo");this.anchorUp()},anchorUp:function(){var a=this;this.get(this.GET_LOGIN_INFO_URL,{},function(b){var c=a.ANCHOR,d=a.LOGIN_INFO;null==b?(d.innerHTML="",d.onclick=d.myRecord=void 0,c.innerHTML="Login",c.onclick=function(b){a.doLogin();return!1}):(d.innerHTML=b.screen_name,d.myRecord=b,d.onclick=function(a){var b=this;UsersHandler.EDITOR.doEdit(this.myRecord.id,
function(a){b.innerHTML=a.value.value.screen_name})},c.innerHTML="Logout",c.onclick=function(b){a.doLogout();return!1})})}},LoginHandler=new EditTemplate(META_LOGIN);var DropdownTagger=$.extend(!0,{},DropdownList);DropdownTagger.CSS_MAIN+=" tagger";DropdownTagger.create_=DropdownTagger.create;
DropdownTagger.create=function(a,b,c,d){a=this.create_(a,b,void 0,d);d=a.myCriteria;d.selectedIds={};d.list=Template.addElem(a,"ul",void 0,this.CSS_MAIN);c&&this.populate(d,c);var e=this;b.doSelect=function(a){var b=a.selection,c;Template.addElem(a.list,"li",e.toCaption(b)).appendChild(c=Template.createAnchor("x",function(b){a.selectedIds[this.myRecord.id]=!1;$(this.parentNode).remove()}));c.myRecord=b;a.selectedIds[b.id]=!0;(c=a.field).value="";c.focus();b=a.callback;b.doPostSelect&&b.doPostSelect(a)};
return a};DropdownTagger.retrieve=function(a){var b=[],c=[];a=a.selectedIds;for(var d in a)a[d]?b[b.length]=d:c[c.length]=d;return{selectedIds:b,removedIds:c}};DropdownTagger.populate=function(a,b){for(var c=a.selectedIds,d,e,g=a.list,h=0;h<b.length;h++)Template.addElem(g,"li",this.toCaption(d=b[h])).appendChild(e=Template.createAnchor("x",function(b){a.selectedIds[this.myRecord.id]=!1;$(this.parentNode).remove()})),e.myRecord=d,c[d.id]=!0};
DropdownTagger.reset=function(a){a.selectedIds=[];a.list.innerHTML=""};var MediaDropdownTagger=$.extend(!0,{},DropdownTagger);MediaDropdownTagger.toCaption_super=MediaDropdownTagger.toCaption;MediaDropdownTagger.toCaption=function(a){return'<img src="'+thumbsPath+a.name+'" width="16" height="16" />&nbsp;'+a.name+" ("+a.id+")"};var TimePicker={CSS_MAIN:"timePicker",SUFFIX:"_time",DEFAULT_INTERVAL:15,MINUTES_IN_DAY:1440,VALUES:{},create:function(a,b,c,d,e){e||(e=this.DEFAULT_INTERVAL);void 0==b&&(b=0);var g=document.createElement("span"),h={name:a,value:b,caller:this,extra:c,callback:d,interval:e};g.appendChild(c=h.hidden=Template.genInput(a,"hidden"));g.appendChild(a=h.field=Template.genSelect(a+this.SUFFIX,this.getValues(e),this.toMinutes(b)));g.className=a.className=this.CSS_MAIN;void 0!=b&&(c.value=(new Date(b)).getTime());
a.onchange=function(a){h.hidden.value=h.value=6E4*parseInt(this.value);d&&d.doSelect&&d.doSelect(h)};return g},toMinutes:function(a){a=new Date(a);return 60*a.getHours()+a.getMinutes()},getValues:function(a){var b=this.VALUES[a];if(b)return b;var c=0,d=0,b=[];do b[c++]={id:d,name:this.toCaption(d)};while((d+=a)<this.MINUTES_IN_DAY);return this.VALUES[a]=b},toCaption:function(a){var b=Math.floor(a/60);a%=60;var c=12>b?"AM":"PM";0==b?b=12:12<b&&(b-=12);10>a&&(a="0"+a);return b+":"+a+" "+c}};var TimestampPicker={CSS_MAIN:"timestampPicker",create:function(a,b,c,d,e){var g=document.createElement("span"),h={name:a,value:b,caller:this,extra:c,callback:d};g.appendChild(a=h.hidden=Template.genInput(a,"hidden"));g.className=this.CSS_MAIN;void 0!=b&&(a.value=(new Date(b)).getTime());h.dateCallback={doSelect:function(a,b){var c;void 0==h.value?c=new Date(b.getFullYear(),b.getMonth(),b.getDate()):(c=new Date(h.value),c.setFullYear(b.getFullYear(),b.getMonth(),b.getDate()));h.hidden.value=h.value=
c.getTime();d&&d.doSelect&&d.doSelect(h)}};h.timeCallback={doSelect:function(a){var b=new Date(a.value);a=void 0==h.value?new Date:new Date(h.value);a.setHours(b.getUTCHours(),b.getUTCMinutes(),0,0);h.hidden.value=h.value=a.getTime();d&&d.doSelect&&d.doSelect(h)}};g.appendChild(DatePicker.create((new Date).getTime(),b,c,h.dateCallback));g.appendChild(document.createTextNode(" "));g.appendChild(TimePicker.create((new Date).getTime(),b,c,h.timeCallback,e));return g}};
